### ISSUE TITLE
Cannot install when specifying `--prefix` on the command line

### ISSUE THREAD

**Issue by tpadioleau** [kokkos/kokkos-fft#136]
When installing with `cmake --install build --prefix some/prefix/path`, it still tries to install in `CMAKE_INSTALL_PREFIX` which defaults to `/usr/local` on my system. It seems to work fine when specifying `CMAKE_INSTALL_PREFIX`.

To reproduce:
```cmake
cmake -DCMAKE_INSTALL_PREFIX=$PWD/install-cmakevar-prefix -B build
cmake --build build
cmake --install build --prefix $PWD/install-cmdline-prefix
```
The directory `$PWD/install-cmdline-prefix` is empty while it should not.

I suspect it comes from variables that read `CMAKE_INSTALL_PREFIX` at configuration time and store the result like
https://github.com/kokkos/kokkos-fft/blob/49200b82ceaf9125b59e23b5fb0867c8a307edda/CMakeLists.txt#L117
These are not updated when `--prefix` is used.

**Comment by yasahi-hpc** [comment]
Thank you for this bug report. 
Does it mean that we cannot set variables to store these paths?

**Comment by tpadioleau** [comment]
> Does it mean that we cannot set variables to store these paths?

I think we should be fine if we just make them relative to `${CMAKE_INSTALL_PREFIX}`:

```cmake
set(LIBDIR cmake/${PROJECT_NAME})
set(INSTALL_INCLUDEDIR ${CMAKE_INSTALL_INCLUDEDIR})
set(INSTALL_LIBDIR ${LIBDIR})
```
