### ISSUE TITLE
Version mismatch

### ISSUE THREAD

**Issue by tpadioleau** [kokkos/kokkos-fft#151]
The `CMakeLists.txt` from release 0.2.0 still exposes version 0.1.0

**Comment by yasahi-hpc** [comment]
Sorry about that. I will make a patch release. It should be release 0.2.1?

**Comment by tpadioleau** [comment]
No worries. I think this is the proper way would be to release a patch indeed. But I tend to think we can take advantage of the early stage of the project and the fact that we released this version a few days ago to delete the package 0.2.0 and create a new one ?

**Comment by tpadioleau** [comment]
Actually, with issue #152 I think releasing a patch is better

**Comment by tpadioleau** [comment]
Actually I think it would be better to have a dedicated PR identifying the change of version. What do you think ?

**Comment by yasahi-hpc** [comment]
It is certainly better
I will make it after completing the fix.
