### ISSUE TITLE
Usage of the `KokkosFFT::Impl` namespace in example 06

### ISSUE THREAD

**Issue by tpadioleau** [kokkos/kokkos-fft#156]
In the example 06, we are currently using symbols from the `KokkosFFT::Impl` namespace, see
https://github.com/kokkos/kokkos-fft/blob/f64a013a8528d8a3bc552d4300105190e078d37a/examples/06_1DFFT_reuse_plans/06_1DFFT_reuse_plans.cpp#L31-L33

I think we should not show any usage of this implementation namespace in the examples.

I can think of different solutions:
- remove temporarily the example,
- move the symbols out of the `Impl` namespace if the feature is ready,
- move the symbols in an experimental namespace.

**Comment by yasahi-hpc** [comment]
Actually, I am considering the option 2.

1. `KokkosFFT::Impl::Plan` -> `KokkosFFT::Plan`
1. `KokkosFFT::Impl::fft_exec_impl` -> `KokkosFFT::execute`
