### ISSUE TITLE
Calling `exec.fence()` in the examples

### ISSUE THREAD

**Issue by tpadioleau** [kokkos/kokkos-fft#157]
How a reader should interpret the calls to `exec.fence()` in the examples ? As we pass `exec` to each function, I don't think they are required to have a valid execution ?

https://github.com/kokkos/kokkos-fft/blob/f64a013a8528d8a3bc552d4300105190e078d37a/examples/01_1DFFT/01_1DFFT.cpp#L25-L50

Should we get rid of them ?

**Comment by yasahi-hpc** [comment]
> How a reader should interpret the calls to `exec.fence()` in the examples ? As we pass `exec` to each function, I don't think they are required to have a valid execution ?

Do you talk about `exec.fence()` in line 28? This may be removed. But, `exec.fence()` in line 32 should be kept.
Internal `fft` functions are bound to the `stream` from the `exec` instance. 
Thus, we need `exec.fence()` after `fft` or `ifft` to ensure that these operations are finished.

**Comment by tpadioleau** [comment]
> Do you talk about `exec.fence()` in line 28? This may be removed.

All `exec.fence()` actually.

> But, `exec.fence()` in line 32 should be kept. Internal `fft` functions are bound to the `stream` from the `exec` instance. Thus, we need `exec.fence()` after `fft` or `ifft` to ensure that these operations are finished.

Why do we need to make the CPU wait for the end of the operation ? As long as we always use the same execution space, operations should be executed in the correct order, isn't it the case ?

**Comment by yasahi-hpc** [comment]
> > Do you talk about `exec.fence()` in line 28? This may be removed.
> 
> All `exec.fence()` actually.
> 
> > But, `exec.fence()` in line 32 should be kept. Internal `fft` functions are bound to the `stream` from the `exec` instance. Thus, we need `exec.fence()` after `fft` or `ifft` to ensure that these operations are finished.
> 
> Why do we need to make the CPU wait for the end of the operation ? As long as we always use the same execution space, operations should be executed in the correct order, isn't it the case ?

It is ensured as long as we use the same execution space. If we access data in a different manner (accessing from MPI functions for example), the execution may not be finished.

**Comment by tpadioleau** [comment]
> If we access data in a different manner (accessing from MPI functions for example), the execution may not be finished.

I agree, as we don't call such functions I would recommend to remove the barriers. I think only the last barrier should remain to ensure the program does not end before the kernels.

We had similar discussions in the documentation of virtual functions in Kokkos, we chose to remove unnecessary barriers.

**Comment by yasahi-hpc** [comment]
> > If we access data in a different manner (accessing from MPI functions for example), the execution may not be finished.
> 
> I agree, as we don't call such functions I would recommend to remove the barriers. I think only the last barrier should remain to ensure the program does not end before the kernels.
> 
> We had similar discussions in the documentation of virtual functions in Kokkos, we chose to remove unnecessary barriers.

I got it. For my examples, I try to make the `Kokkos` examples identical to the `python` examples. 
I will make a PR to remove unnecessary barriers.
