### ISSUE TITLE
Support of unmanaged views

### ISSUE THREAD

**Issue by tpadioleau** [kokkos/kokkos-fft#160]
Linked to #158, if KokkosFFT does not handle memory allocation of output views, the support of unmanaged views should be transparent.

In either case, up to my knowledge the memory trait `Kokkos::Unmanaged` is optional. I don't think we can only rely on the static value `OutViewType::memory_traits::is_unmanaged`.

https://github.com/kokkos/kokkos-fft/blob/f64a013a8528d8a3bc552d4300105190e078d37a/common/src/KokkosFFT_transpose.hpp#L100

**Comment by yasahi-hpc** [comment]
> Linked to #158, if KokkosFFT does not handle memory allocation of output views, the support of unmanaged views should be transparent.
> 
> In either case, up to my knowledge the memory trait `Kokkos::Unmanaged` is optional. I don't think we can only rely on the static value `OutViewType::memory_traits::is_unmanaged`.

Sure. What is the better way to support unmanaged views?

**Comment by tpadioleau** [comment]
Actually I think it is an artefact of our internal functions. Slightly reworking the implementation should remove the need of `if constexpr (!OutViewType::memory_traits::is_unmanaged)`. I need to check though.

**Comment by yasahi-hpc** [comment]
Makes sense. I guess some functions can be removed while keeping the same capability of APIs
