### ISSUE TITLE
Usage of  internals of Kokkos

### ISSUE THREAD

**Issue by tpadioleau** [kokkos/kokkos-fft#166]
https://github.com/kokkos/kokkos-fft/blob/1fd4a8590a4cce207c4bdb7fc39d2b5f59fd79d7/common/src/KokkosFFT_traits.hpp#L244-L250

We are relying on `Kokkos::MemoryTraits::impl_value` I don't think we should.

**Comment by masterleinad** [comment]
> Thus, it seems that this is identical to `Kokkos::MemoryTraits<0>` which is managed.

That's what you want, right? The code is supposed to remove the `Unmanaged` trait (and keep all other traits). Would just using default traits a problem?

**Comment by tpadioleau** [comment]
Yes I think `T::memory_traits::impl_value & ~unsigned(Kokkos::Unmanaged)` is supposed to make it a managed view, keeping the traits untouched.

> Would just using default traits a problem?

Actually I don't think we need to keep other traits so default would be good.
