### ISSUE TITLE
Cmake configure step, Error during link interface

### ISSUE THREAD

**Issue by W-Wuxian** [kokkos/kokkos-fft#209]
# Bug description
After installing kokkos, while using cmake to build kokkos-fft with the following command:
```bash
cmake -B build -S kokkos-fft-0.2.1 -DCMAKE_PREFIX_PATH=kokkos-4.4.01 -DCMAKE_INSTALL_PREFIX=${KOKKOSFFT_INSTALL_PREFIX} -DKokkosFFT_ENABLE_EXAMPLES=ON -DKokkos_ENABLE_OPENMP=ON -DKokkosFFT_ENABLE_HOST_AND_DEVICE=ON
```
I got the following Error:
```bash
-- Enabled Kokkos devices: OPENMP
-- KokkosFFT version: 0.2.1
-- KokkosFFT TPLs:
--     Host Parallel: FFTW_OPENMP
-- Configuring done (0.1s)
CMake Error at common/src/CMakeLists.txt:39 (target_link_libraries):
  The link interface of target "common" contains:
    FFTW::Float
  but the target was not found.  Possible reasons include:
    * There is a typo in the target name.
    * A find_package call is missing for an IMPORTED target.
    * An ALIAS target is missing.
-- Generating done (0.0s)
CMake Generate step failed.  Build files cannot be regenerated correctly.
```
# Possible fix
Looking at  `kokkos-fft-0.2.1/common/src/CMakeLists.txt LINE 39` we have the following:
```bash
target_link_libraries(common INTERFACE FFTW::Float FFTW::Double FFTW::FloatOpenMP FFTW::DoubleOpenMP
```
Since  `FFTW::Float` was not found, a possible fix is to remove it as follow:
```bash
target_link_libraries(common INTERFACE FFTW::Double FFTW::DoubleOpenMP)
```
**However why FFTW::Float was requested?**
# Modules and softwares version Used to build kokkos-fft
`1) gcc/13.2.0   2) OpenMPI/5.0.3   3) fftw/gcc-OpenMPI/3.3.10   4) cmake/3.31.0 5)kokkos-4.4.01 6)kokkos-fft-0.2.1`
Where fftw was build to generate double precision (the default one), mpi and OpenMP libraries (libfftw3_mpi.so and libfftw3_omp.so).

**Comment by yasahi-hpc** [comment]
For the moment, we assume that `fftw` is installed with `fp32` and `fp64`. 
This is for the consistency with other libraries which support both `fp32` and `fp64`.

Technically, we can add an option for `fftw` to compile only with `fp64`.
If you modify the `kokkos-fft-0.2.1/common/src/CMakeLists.txt` in your manner, does it compile?

**Comment by W-Wuxian** [comment]
Yes it does. Thanks for the clarification.
