### ISSUE TITLE
`cufftHandle` is created twice

### ISSUE THREAD

**Issue by tpadioleau** [kokkos/kokkos-fft#211]
I suspect we create twice the CUDA plan, once with `cufftCreate` and again with `cufftPlan1d` https://github.com/kokkos/kokkos-fft/blob/4b82641937cda86d56a5137ed32ba9b4a2940026/fft/src/KokkosFFT_Cuda_plans.hpp#L39-L54

From what I understand in the cuFFT documentation, we should either
- call `cufftCreate` then `cufftMakePlan1d`, https://docs.nvidia.com/cuda/cufft/index.html?highlight=cufftMakePlan1d#cufftmakeplan1d
- call directly `cufftPlan1d`, https://docs.nvidia.com/cuda/cufft/index.html?highlight=cufftMakePlan1d#cufftplan1d

Notice that both `cufftCreate` and `cufftPlan1d` take the plan by pointer whereas `cufftMakePlan1d` takes it by copy.

**Comment by yasahi-hpc** [comment]
That is true. I will make a fix
